### ISSUE TITLE
** (FunctionClauseError) no function clause matching in Explorer.PolarsBackend.Shared.normalise_dtype/1 

### ISSUE THREAD

**Issue by vishal-h** [elixir-explorer/explorer#720] opened 2023-10-14 04:55 UTC
Downloaded this hf/dataset as a parquet file https://huggingface.co/datasets/aqubed/kub_tickets_small

Dropped into livebook 

```
df =
  Kino.FS.file_spec("train-00000-of-00001-47868532d4f55873.parquet")
  |> Explorer.DataFrame.from_parquet!(lazy: true)
```
This is the error stack

```
** (FunctionClauseError) no function clause matching in Explorer.PolarsBackend.Shared.normalise_dtype/1    
    
    The following arguments were given to Explorer.PolarsBackend.Shared.normalise_dtype/1:
    
        # 1
        "list[str]"
    
    Attempted function clauses (showing 10 out of 15):
    
        def normalise_dtype("binary")
        def normalise_dtype("bool")
        def normalise_dtype("cat")
        def normalise_dtype("date")
        def normalise_dtype("time")
        def normalise_dtype("datetime[ms]")
        def normalise_dtype("datetime[ns]")
        def normalise_dtype("datetime[μs]")
        def normalise_dtype("duration[ms]")
        def normalise_dtype("duration[ns]")
        ...
        (5 clauses not shown)
    
    (explorer 0.7.1) lib/explorer/polars_backend/shared.ex:157: Explorer.PolarsBackend.Shared.normalise_dtype/1
    (elixir 1.15.6) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (elixir 1.15.6) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
    (explorer 0.7.1) lib/explorer/polars_backend/shared.ex:80: Explorer.PolarsBackend.Shared.create_dataframe/1
    (explorer 0.7.1) lib/explorer/polars_backend/lazy_frame.ex:176: Explorer.PolarsBackend.LazyFrame.from_parquet/3
    (explorer 0.7.1) lib/explorer/data_frame.ex:755: Explorer.DataFrame.from_parquet!/2
    #cell:rgehv7ftpvdvvvzo26acv3cncaafmoub:3: (file)
```

**Comment by josevalim** [comment] 2023-10-14 07:35
Duplicate of #296, we don't support list dtypes yet, we will probably look into this soon.

**Closed** 2023-10-14 07:52 UTC
